[options]
packages = find:
namespace_packages = ckanext
install_requires =
include_package_data = True

[options.entry_points]
babel.extractors =
                 ckan = ckan.lib.extract:extract_ckan

[options.extras_require]

[extract_messages]
keywords = translate isPlural
add_comments = TRANSLATORS:
output_file = ckanext/manage_tags/i18n/ckanext-manage_tags.pot
width = 80

[init_catalog]
domain = ckanext-manage_tags
input_file = ckanext/manage_tags/i18n/ckanext-manage_tags.pot
output_dir = ckanext/manage_tags/i18n

[update_catalog]
domain = ckanext-manage_tags
input_file = ckanext/manage_tags/i18n/ckanext-manage_tags.pot
output_dir = ckanext/manage_tags/i18n
previous = true

[compile_catalog]
domain = ckanext-manage_tags
directory = ckanext/manage_tags/i18n
statistics = true
